title: MOE Classroom of the Future
url: https://girlwithkaleidoscopeeyes.com
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#578ffe"
  secondary-color: "#ffb500"
  media-colors:
    - title: media-color-one
      color: "#ff0082"
    - title: media-color-two
      color: "#ff0082"
    - title: media-color-three
      color: "#ff0082"
    - title: media-color-four
      color: "#ff0082"
    - title: media-color-five
      color: "#ff0082"
description: A Ministry of Education Singapore Educational Technology Division
  and Information Technology Division effort leveraging design thinking and
  other human-centric methodologies to redesign teaching and learning for
  teachers and students.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d34sxxwkzr355u.amplifyapp.com
prod: https://master.d34sxxwkzr355u.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
